Syntax ::=
    FastTransferCommand FastTransferOptions

FastTransferCommand ::=
    ( "'.\FastTransfer.exe'" | "'./fasttransfer'" )

FastTransferOptions ::=
    "--sourceconnectiontype" SourceConnectionType
    SourceConnectionParameters
    SourceInfos
    "--targetconnectiontype" TargetConnectionType
    TargetConnectionParameters
    TargetInfos
    (|ParallelParameters)
    (|MappingParameters)
    (|LogParameters)
    (|LicenseParameters)


SourceConnectionType ::=
    ( "clickhouse"
    | "duckdb"
    | "hana"
    | "mssql"
    | "mysql"
    | "nzsql"
    | "odbc"
    | "oledb"
    | "oraodp"
    | "pgcopy"
    | "pgsql"
    | "teradata"
    )

SourceConnectionParameters ::=
    (( 
      "--sourceserver"
      ("Host"
       | "Host:Port" | "Host\InstanceName" | "Host:Port/TNSService" ) 
    (|"--sourceprovider" OLEDBProvider)
      |("--sourcedsn" DSNName)
    )
    ( "--sourcetrusted"  | ( "--sourceuser" "Username" "--sourcepassword" "Password" ))
      "--sourcedatabase" "Database")
    
  | ( "--sourceconnectstring" ConnectString )
 

SourceInfos ::=
    (( "--sourceschema" SchemaName "--sourcetable" TableName) | ("--query" Query | "--query" Query "--sourceschema" SchemaName "--sourcetable" TableName)  | ("--fileinput" FilePath | "--fileinput" FilePath "--sourceschema" SchemaName "--sourcetable" TableName))
 
 
TargetConnectionType ::=
    ( "clickhousebulk"
    | "duckdb"
    | "hanabulk"
    | "msbulk"
    | "mysqlbulk"
    | "nzbulk"
    | "orabulk"
    | "oradirect"
    | "pgcopy"
    | "teradata"
    )

TargetConnectionParameters ::=
    (( 
      "--targetserver"
      ("Host"
       | "Host:Port" | "Host\InstanceName" | "Host:Port/TNSService" ) 
    )
    ( "--targettrusted"  | ( "--targetuser" "Username" "--targetpassword" "Password" ))
      "--targetdatabase" "Database")
    
  | ( "--targetconnectstring" ConnectString )

TargetInfos ::=
     "--targetschema" SchemaName
     "--targettable" TableName
	 (|"--loadmode" ("Append" | "Truncate"))
	 (|"--batchsize" "BatchSizeInt")

ParallelParameters ::=
    "--method" ( "None"| ((("Random" | "DataDriven" | "RangeId" | "Ntile" ) "--distributeKeyColumn" "KeyColumn") | "Ctid" | "Rowid"  ) "--degree" Degree)

MappingParameters ::=
 "--mapmethod" ("Position" | "Name")

LogParameters ::=
    (|"--runid" RunId)
    (|"--settingsfile" SettingsFile)

LicenseParameters ::=
"--license" (licenseFile|licenseUrl)
